import pandas as pd
import numpy as np

# Original list of hobby and interest strings
hobbies = [
    "Coding, Reading",
    "Dancing, reading",
    "Watching Movie ",
    "Chess",
    "Coding, watching movies ",
    "Reading, Cooking,Crocheting",
    "Chess ",
    "Basketball ",
    "Cricket, Reading Novels",
    "Reading, Writing poems, listening songs",
    "Watching cricket,playing videogames,acting",
    "Outing, dancing ,etc",
    "Spending time with loved ones",
    "Reading, organizing ",
    "Dancing and singing ",
    "Singing and dancing ",
    "Esports",
    "Travelling trekking reading Books",
    "Walking reading ",
    "Dancing, computing with people, collection of articles ",
    "Cooking and reading",
    "Reading Books and Drawing or Painting ",
    "Sports",
    "Cooking, Reading Novels",
    "Gaming, Cricket, football , Spending time with friends and family ",
    "Dance and travel ",
    "Reading books ",
    "Listen music",
    "Playing Football and guitar also drawing and listening to music ",
    "Music, movies",
    "Sports and exploring new places",
    "Making designs, Drawing, dancing, reading, travelling, cooking",
    "Reading ",
    "Gaming ",
    "Reading books, astronomy, sports",
    "Reading, Singing, Travelling ",
    "Dancing and Learning ",
    "Doodling , drawing",
    "Travelling,dancing,cooking,interacting new people,exploring new things,learning everything which is difficult,shopping",
    "Elocution ",
    "Reading and interests is in study of economics , business and finance ",
    "Reading, writing ",
    "Exercising, ",
    "Singing, travelling, dancing , learning new skills ",
    "Art ",
    "Sketching, travelling",
    "Swimming, Taekwondo, tracking ",
    "Traveling ",
    "Reading books & travelling ",
    "Art, study related astronomy, travelling ",
    "Listening music, coding, online games",
    "Miniature design, Classical Basari Instrument Playing ",
    "Reading novels, webnovels, fiction and non fiction, gaming, chess",
    "Anime, football, cricket, movie, ",
    "Anime, Cricket, Defence ",
    "Teaching ",
    "Sketching, reading ",
    "Painting, diy",
    "Knowing about politics and watching science frictional movies",
    "Gaming, bike riding, swimming ",
    "Reading, travelling",
    "Playing games, playing basketball, reading books",
    "Dancing, basic cooking",
    "Music",
    "Photography ",
    "Basketball and music ",
    "Travelling ",
    "No",
    "Dancing, singing, acting ",
    "Singing ",
    "Reading, program language, entrepreneur ",
    "Trading and Swimming ",
    "Travelling ,Singing, Cooking, Swimming, Playing Badminton.",
    "Singing and listening Songs, travelling, reading self- help books",
    "Music,Dance,Sleep,Travel",
    "I enjoy painting, travelling and reading books",
    "Archery",
    "Sketching and painting, riding bikes",
    "Playing games and sports",
    "Cars",
    "Trekking swimming karate painting reading ",
    "Grading, Fitness Activities, Travelling ",
    "Cricket",
    "Motorsports",
    "Dancing, listening music ",
    "Chess and dancing",
    "No such hobbies. I loke to do what I am doing nicely and perfectly.",
    "Reading books and painting ",
    "Watching movies and painting ",
    "Sports, dance, travelling, trekking, cooking ",
    "Drawing ,sketching ,reading",
    "Books",
    "Like to play video games",
    "Fitness and Driving",
    "Reading fiction books, watching netflix",
    "Playing cricket, watching movies",
    "Reading and watching webseries ",
    "Playing chess and stock market research ",
    "Dancing and reading ",
    "Music ",
    "Playing games",
    "Hobby - playing games , watching movies. Intrests - learning new skills",
    "Playing games, reading books",
    "Badminton, sketching, drawing",
    "Sketching and writing ",
    "My hobbies are watching movies/webseries, playing cricket, travelling, tracking ",
    "Playing volleyball ",
    "Gaming",
    "Finance, future, cricket, practical ",
    "Good interaction,communication, cricket ",
    "Reading, Games, Music, Learning ",
    "Playing tabla and chess",
    "Exploring new places ",
    "Photography, basketball",
    "Sketching , reading ",
    "Reading cooking sketching ",
    "Reading books ,treking ,farming and coding. ",
    " I like singing  and dancing",
    "product videography ",
    "Acting, cooking",
    "Painting, dancing ",
    "Calisthenics, sketching , dancing",
    "Reading and Drawing ",
    "Football, video games, music",
    "Reading and Writing poetry ",
    "I like Aerodesigning, I like listening podcasts, I like playing outdoor games",
    "Trekking and I am interested in coding ",
    "Volleyball , Football ",
    "Reading, learning new things,site work, playing kabbadi",
    "Cricket , travel ",
    "I like to write poetry and sometimes sing",
    "Cooking, Travelling, reading ",
    "Drawing, baking,cooking, rangoli making etc",
    "Paintings , designing and organizing home , interest in trying new things",
    "Cooking and planning trips",
    "..",
    "Watching movies, playing chess ",
    "foot ball ",
    "Trying new things ",
    "Adventure, trekking, swimming, reading, vacation ",
    "Sports like kabbadi, cricket. Hobbies are dancing, reading, gardening. ",
    "Football, watching anime",
    "Sports ",
    "Sketching",
    "Making reels photoholic",
    "Listening",
    "competitive gaming (ESPORTS) , music ",
    "Playing outdoor games & love to watch sports competitions",
    "Singing, Reading, Travelling, Games, Movies ",
    "Learning management skills & organizing events",
    "Playing cricket ",
    "Travelling and adventure ",
    "Playing ,Treaking",
    "Coding ",
    "Love to express thoughts by writing, Singing ",
    "Soccer . Chess",
    "Running",
    "There are many but kez hobbies is playing badminton and working for business ideas",
    "Trekking & Sports",
    "Playing Football ",
    "Trekking and sports",
    "Playing Basketball ",
    "Cooking, dancing",
    "Workout ",
    "Badminton",
    "To learn new things and cricket for physical fitness.",
    "Learning new skills, sketching and painting",
    "Sketching, Dancing",
    "Dancing ",
    "Imagination, dancing, writing, interest in software testing IT or non IT",
    "Hobbie is to play volleyball and I am a dhol vadak",
    "Reading, coding ",
    "Playing chess",
    "Playing Cricket",
    "Playing chess , listening music, travelling ",
    "1)GYM 2)Cricket 3)Taking care of my appearance",
    "Learn new language ",
    "Coding,Playing games,reading",
    "Solo Traveling",
    "I like to read novels",
    "Traveling and sports ",
    "Guitar",
    "Football,Athletics and badminton and solving maths calculations",
    "Dancing and cooking ",
    "Painting, reading, cooking, dancing,",
    "Listening to music and dance ",
    "Playing online games, exploring new business ideas, exploring new things, travelling, farming",
    "Painting, watching movies",
    "Cricket ",
    "Playing cricket, reading books, mission gadkot,treking",
    "Learning new languages ,",
    "Swimming, Painting, Cooking ,Travelling ",
    "Art and playing games",
    "Hobbies - Dance  Intrest- Trekking ",
    "GYM,Learning new Skills",
    "Reading Music drawing dance ",
    "Drawing ",
    "Travelling, reading novels ",
    "Playing sports",
    "learning new skills, playing sports(outdoor)",
    "playing cricket, gym, coding ",
    "Reading , playing cricket, coding ",
    "Play games",
    "Cricket,chess, reading books.",
    "Cricket, reading books, chess",
    ". ",
    "Computer programming ",
    "Art ,browsing ",
    "Playing Cricket ",
    "Music dance outdoor games",
    "Outdoor activities and reading books",
    "Making mechanical projects",
    "sketching, sports, outings ",
    "Art and craft",
    "Dance and singing ",
    "Traveling and Football ",
    "Reading , watching serial ",
    "Dancing, Travelling ",
    "Drawing",
    "Gym",
    "Singing, Coding ",
    "Travelling, exploring, foodie, living life",
    "Sports ,dancing , bike riding and tracking ",
    "Reading books",
    "MUSIC AND TRAVELLING ",
    "writing , playing games",
    "Dancing and playing ",
    "Film making ",
    "Singing, dancing, daily kitchen works and... I love to read books",
    "Football, music",
    "Coding, exploring, watching movies",
    "Dancing, Exploring new things and travelling ",
    "Dancing & art",
    "Singing",
    "Getting knowledge about different businesses ",
    "Watching movies ",
    "nan",
    "Playing badminton and reading books ",
    "Acting , Dancing",
    "Conding and Body Building ",
    "Singing and coding",
    "Innovative new ideas into projects and gaming in free time",
    "Cricket ,swimming",
    "Play draw swim Love being in farm travel",
    "Solving Cubes",
    "Interested in playing games ",
    "Sports and music",
    "Football and pubg",
    "Listening music, observing things.",
    "Dance travel",
    "Playing ground games",
    "Working out, Reading ",
    "Dancing, writing, listening music, travelling, shopping ",
    "Social service , Design , Event Mangement , Adventure activity ",
    "Travelling, watching TV and phone ",
    "Tracking, watching phone and TV",
    "Football",
    ".",
    "Dance",
    "Classical dance",
    "Cars, travel , Tv , Cartoons,bikes,food,time spending with family ",
    "Watching Movies ",
    "Basketball harmonium singing dancing",
    "I like to play cricket ,to study",
    "Singing and listening eng poetries",
    "Playing Badminton ",
    "exploring ",
    "Reading and listening to music",
    "Listening Music",
    "LISTENING MUSIC",
    "Reading,Swimming,Trekking",
    "Playing and learn something new like any skill or work in any industry .",
    "Listening music, reading ",
    "Learning new things, playing an harmonium, reading books , teamwork ",
    "Photography, Editing, Traveling",
    "Cricket, swimming ",
    "Coding",
    "Sketching ",
    "Music Production, Volleyball, Game development ",
    "My hobbies and interests include dancing, drawing, painting, sketching, and sports. I enjoy communicating with people, offering advice, and helping them solve issues in their lives. I also have a keen interest in cooking and experimenting with new dishes, as well as exploring opportunities in communication-related fields",
    "Hobby is Dance and interest to know the new things or technologies ",
    "Playing cricket and treking ",
    "Travelling reading dancing adventures exploring new things ",
    "Travelling and Anime watching ",
    "Trekking, traveling and interested in learning geography and current affairs",
    "Photography And VFX",
    "Playing chess, badminton, online games, travelling",
    "Physical sports, trekking ",
    "reading books and watching thriller movies and cricket",
    "Swimming and Event Managing ",
    "Watching web series, Travel, bike riding ",
    "Painting",
    "Interest in listing song ",
    "Movies",
    "Sports and entrepreneurship ",
    "Watching movies, playing games",
    "Playing and coding ",
    "Dancing, journaling ",
    "Dancing, swimming, singing",
    "Networking and sketching ",
    "Playing  outdoor game's ",
    "Table tennis ",
    "Reading and table tennis ",
    "Traveling, Listening Music ",
    "Dancing and drawing ",
    "Drawing, Digital Illustration, 2D Animation",
    "Reading story books ",
    "Reading books Data Science Singing classical songs ",
    "Watching YouTube ",
    "My hobby is reading books, listening songs",
    "Ny hobby is reading, listening songs, cleanliness ",
    "Driving,reading ",
    "Dancing and reading books",
    "Making creativity,watching movie",
    "cooking,treking",
    "Sports, General knowledge question solving",
    "Playing kabaddi ",
    "Football, Singing, Gaming, workout",
    "Football, Gaming, Singing",
    "Cricket and gym ",
    "Study, sport, music , reading ",
    "Ho learn new technologies ",
    "Volleyball, Reading Books",
    "Travelling, swimming",
    "Football & Gaming ",
    "Interest in vehicles design & manufacturing ",
    "Playing",
    "Guitarist , cricket , driving ",
    "Cooking and aero modelling ",
    "Cricket, Project work, Chess.",
    "Karate, Chess, Swimming, Badminton and Cricket ",
    "Reading and drawing ",
    "Sports, drawing, dancing and I have interest in coding a d extracurricular activities",
    "Online gaming, drawing , sweeming ",
    "Traveling, reading ,Helping",
    "Arts and drawing ",
    "Playing crickets travelling etc",
    "Cinema ",
    "Reading carrier oriented Books and businessmen biography ",
    "Singing and Paino Player",
    "Dance. Read books ",
    "Football , gym freak",
    "Yes",
    "Dancing, reading books ",
    "Reading novels",
    "Reading book",
    "Wicket keeper ",
    "Calligraphy, lettering , drawing, writing, speaking , ",
    "Exploring,team work ",
    "Drawing, Painting, Art and Crafts, Photography, Exploring ",
    "Playing Games ",
    "Reading, exploring",
    "Playing football and doing workout ",
    "Playing football and chess , video editing ",
    " sports and courses",
    "Spending time with pets  ,colouring ,trying something new .",
    "I love to dance sometimes ",
    "Cooking,dancing,drawing",
    "Cars, automobiles, sports",
    "Volleyball, keeping up with the current technological trends",
    "Listening music,reading sci-fi novels, watching documentaries,pc games",
    "Swimming, watching movies, Coding ",
    "Playing sports ",
    "Travel, Collecting old coins, Watching documenteries ",
    "Reading, swimming & playing badminton ",
    "Table tennis ,Swimming ",
    "Interests : Working out at the gym.",
    "Listening music",
    "Painting, travelling ",
    "Drawing, reading ",
    "Reading books, playing games, listening music",
    "Chess, Basketball, listening to music",
    "Not any specific.",
    "My hobbies is mehandi rangoli sports and dance",
    "Nope ",
    "I am part time cricketer for club ",
    "Movies , Sport",
    "Sport",
    "I am a tech enthusiast, and really interested in Cyber Security field. I recently got selected at IIT Guwahati's Cyber Security Expert Mini Credit program and pursuing this degree from IIT Guwahati. I am also a Singer and love singing. Due to my strong leadership and management skills, I have been elected as Vice-president of College's first Cyber Security Students Club, Protocol, which is a college level Club.",
    "Playing video games or cricket or maybe physical activities ",
    "Singing songs, campaign, teamwork, cooking ",
    "Playing cricket,using net browsing etc",
    "Dancing , listening to music etc",
    "Reading books , ",
    "Networking, community service, learning language ,yoga, cooking ",
    "Learning new skills and interested in volunteering, teamwork ",
    "trekking, travelling, cooking and playing sports",
    "Listening music ",
    "Reading",
    "Nothing",
    "Long Walks with friends & Bike Rides",
    "Playing cricket",
    "Gym cricket",
    "sports like badminton and skating",
    "Singing , drawing",
    "Photography , swimming , trekking , painting and drawing , badminton , volleyball .",
    "I play badminton and swim ",
    "I'm into sports. Love playing badminton. Been a national skater and a state swimmer",
    "Chess, cricket, badminton",
    "Drawing and playing games ",
    "Working out, hanging out with family and friends, sports like cricket,kabaddi, Playing cards, Video games.",
    "Writing poems ",
    "I like reading, drawing",
    "Playing flute",
    "Travelling and playing mobile games ",
    "Travel , Dance ",
    "Cricket, Gaming, Coding ",
    "Reading books,Cricket",
    "Arts, craft, singing, sketching ",
    "Reading news and articles related to current affairs,",
    "Drawing, writing shayari",
    "Watching Cricket match",
    "Make a Best Software engineer",
    "Sketching, travelling ",
    "Interested in learning new skills ",
    "Doing workout ",
    "Acting, Sports, Travelling & Riding, Dance, Cooking",
    "Traveling and playing cricket",
    "Listening to songs, gym workout, exploring nature, etc.",
    "reading books , writing, singing, coding ",
    "Dancing and sports ",
    "Listening to music ",
    "Learning new skills ",
    "Watching and playing cricket, Listening Music, travelling ",
    "Watching cricket and playing cricket, Listening Music ",
    "I love cooking and eating. Also I'm interested in singing bollywood songs as well as classical ",
    "Love cooking ",
    "Watching movies and watch collections",
    "cooking",
    "Chess , reading novels, kabaddi",
    "Playing football, event management, etc",
    "Singing, crafting, sketching and reading ",
    "Listening to music, watching movies.",
    "Bike riding and trekking ",
    "Cricket, Music, Reading ",
    "Reading and playing ",
    "Badminton ",
    "Playing and watching cricket ",
    "Trekking, Reading books, cycling ",
    "Traveling",
    "Travelling",
    "Drawing and designing",
    "Football, drawing, online games, coding ",
    "I like to read books ",
    "Cooking, dancing ",
    "Playing tabla",
    "Painting and photography ",
    "Reading books and drawing ",
    "Exercise, Running, cricket, football, volleyball, Swimming ",
    "Hobbies - None, Interests - Anime, Foreign policy, Geoplitics ",
    "Reading, travel",
    "Comedy",
    "Acquiring information about social activities and current affairs helps in staying informed",
    "Trekking",
    "Football and reading ",
    "Gaming, Sports",
    "Reading a books ",
    "Reading and exploring",
    "Listening Music, Travelling ",
    "Space research and traveling ",
    "producing music",
    "Car racing , hair care and skin care",
    "Swimming",
    "Trading and weight training ",
    "Playing badminton",
    "Swimming playing cricket football music etc",
    "Graphic design , video editing, Ms office works",
    "-",
    "Football, Swimming ",
    "Design ",
    "Travelling, sketching ",
    "Listening to music , reading ",
    "Playing football, listening podcast ,organizing events",
    "Trading , poetry ",
    "Driving cars ",
    "Swimming, Travelling, Art & Craft, Farming ",
    "Reading and travelling ",
    "Book reading and Crafting",
    "Read books",
    "Singing, dancing ",
    " ",
    "Watching Sports ,Drawing ,Cricket",
    "Playing badminton ",
    "Cycling, listen music",
    "Read novel and books",
    "Watching movies and listening music",
    "Basketball , sketching , cricket, football,etc",
    "F1 and Books",
    "Read books ,play games ",
    "Playing outdoor games, Swimming, Reading ",
    "I interested in achiving good skills in mechanical field . I am interested to study softwares about mechanical engineering. ",
    "Reading cooking ",
    "Like to play karate ",
    "Sketching, painting, reading, learning new skills makes mi excited ",
    "Listening to music and playing video games ",
    "Dancing, watching movies ",
    "Sports, Gaming, Rides",
    "Cooking food, any sports ",
    "Swimming ",
    "Learning new things ",
    "Reading, sketching,movies,music",
    "Playing football, athletics,arts",
    "Walking",
    "Drawing dancing ",
    "Singing dancing",
    "I like to read . I like to visit new places. ",
    "I like to visit new places . I like to learn new things.",
    "Hehehe ",
    "Studing,playing,art,cooking ",
    "Coding , cricket",
    "Dancing, playing basketball ",
    "To being an Cricketer ",
    "Like to learn more languages ",
    "Listening to music",
    "1) I like to play Guitar 2) I love to Travel 3) I love to speak with new people",
    "Watching Series, Reading Books",
    "Dancing, listening music, create new things, interior designing ",
    "Dancing, listening music, create new things ",
    "Reading Books, Playing Cricket, Coding ",
    "To learn new things",
    "Rifel Shooting ",
    "Hobbies: reading, yoga , interests: Badminton ",
    "Designing,art, dancing ",
    "Reading books and exploring the new things ",
    "Playing Guitar , Listening to Songs ",
    "Playing cricket and other outdoor activities ",
    "Singing , experiencing new work , reading ",
    "Cricket, travelling, kabaddi, listening music, etc.",
    "Gym coding",
    "Writing ",
    "Gym, Trekking, Discussion on politics and world affairs, Technology, farming",
    "Cooking & travelling ",
    "SPORTS ",
    "Hobbies: To play outdoor sports, watch movies, etc.      Interests: To run a Business.",
    "Play cricket and kabbadi ",
    "Playing outdoor games ",
    "Na",
    "Playing cricket kabbadi ",
    "Watch sports, tinkering",
    "Sleeping",
    "Gameing , listening music, watching movies,  talking with friends ",
    "Reading books, watching movies, travelling and exploring different places, listening music",
    "Dance ",
    "Sports and reading ",
    "Bike Riding  , Rap Song , Farming ",
    "Coding, tech field, dance cricket, tennis, interest in buisness and finance ",
    "Sleeping ",
    "Automobile ",
    "Travelling, Dancing",
    "I love playing chess",
    "Painting and crafting",
    "ART AND CRAFT",
    "I like to play Cricket in my free time.",
    "Football and anime ",
    "Painting, Singing, listening to music",
    "Reading books,dancing, singing, karate ",
    "Listening music, drawing",
    "Playing outdoor game's ",
    "Listening music,Drawing ",
    "Travelling, Watching Movies ",
    "Reading , chess , art ",
    "Aquarium",
    "Drawing, listening music ",
    "Football, Calisthenics and Cycling",
    "Entrepreneurship, Cricket ",
    "Sports, dancing, reading books",
    "Listening music, watching series/YouTube, ",
    "Gym for healthy physic",
    "Read books ",
    "Gym for healthy physic ",
    "Building circuits, playing football, basketball",
    "Sketching,art, content creator ,editing,designier",
    "Health & music",
    "Traveling and Driving",
    "I love Sketching,music,travel ",
    "Drawing & playing Badminton ",
    "Traveling and playing football ,badminton ",
    "Drawing, Dancing ",
    "SANDART ,Singing, acting , drawing, participate in dramas in cultural ",
    "My hobbies are drawing, like to swim and travel (explore new places) with friends",
    "Writing, listening songs, gaming ",
    "Drawing, playing sports ",
    "Data Analytics ",
    "Cooking,reading",
    "Cooking dancing reading ",
    "Playing Cricket and BGMI",
    "Hobbies playing games intrest cyber security ",
    "Traveling,gaming",
    "Maths",
    "Nothing ",
    "Hiking ",
    "Can play each and every sports.. An athlete… good leadership quality… volleyball district player.. ",
    "Watching movies",
    "Watching Movies, Swimming, Playing Games",
    "I have interest in learning new things ",
    "Reading books,trecking ",
    "No option ",
    "Dancing,playing ",
    "Dancing",
    "Studying people and society ",
    "Geopolitical study",
    "playing cricket, football etc",
    "Music, Sports, Theatre",
    "Cricket, kabaddi ",
    "Chess cricket online video games",
    "Reading story books & playing video games are my hobbies ",
    "Painting ",
    "I m interested in occult sciences like palmistry, astrology, numerology.",
    "Painting, music listening, exploring new things ",
    "Painting, listining music ",
    "Dance ,travel, reading, listening music",
    "yoga and meditation ",
    "Playing a Cricket, Making interesting new thing or projects",
    "Musical instruments playing ",
    "Playing guitar, Reading",
    "Sketching and playing games",
    "Trekking ",
    "Cooking, Learning",
    "Playing karate,boxing, aero modelling etc",
    "Music and reading ",
    "Listening Music ",
    "Gymnasium ",
    "Gaming , Listening To Music ",
    "Waching novel ",
    "Listing song, try for new things ",
    "Listing song ",
    "Currently interested in learning stock marketing ",
    "Playing Kabbadi",
    "In Gaming ",
    "Reading and listening online story ",
    "Sports and cinema ",
    "Learning new musical instruments ",
    "drawing random things",
    "drawing",
    "To watch funny videos ",
    "Singing Reading",
    "Playing Cricket 🏏",
    "Sketching, dancing ",
    "Drawing, mehndi , reading Book, playing tennis and guitar ",
    "Kdrama , reading books ",
    "Drawing, art ,dance , badminton, listening music",
    "Travelling, dancing ",
    "Exploring new things ",
    "Painting Swimming Sketching ",
    "For many activities which is homeless ",
    "Drawing and games",
    "Gaming,sketching",
    "Dancing and watching movies",
    "Love to write stories , reading the books ",
    "Playing cricket,vollyball",
    "Playing karate ",
    "Cooking ",
    "Listening Songs",
    "Don't know ",
    "Reading, Hard work for better future ",
    "Drawing, painting ",
    "I like to play cricket ",
    "playing games",
    "Gym ",
    "Like to travel and making creative things ",
    "Sketching , Cooking ",
    "Physical fitness and watching podcast of army veteran",
    "Badminton and dancing ",
    "Watching TV ,Reading news paper",
    "Dance, travel ",
    "Sky watching and Sports",
    "Creativity ",
    "Join the MNC",
    "Physical activities like sports (basketball, soccer, baseball), outdoor adventures (hiking, camping, fishing), creative pursuits (drawing, painting, playing a musical instrument), building and collecting (model cars, Lego), gaming (video games, board games), martial arts, coding, photography, cooking, and even gardening depending on their interests and age. ",
    "Guitar and Sketching",
    "Doing something special for my parents ",
    "Some special do for family ",
    "Playing any sports ",
    "ESports",
    "Coding and drawing ",
    "Sketching, playing outside games, dancing",
    "I like to travelling and see the most very good  and different places",
    "Playing cricket and badminton ",
    "Love painting and travelling ",
    "Playing cricket and baseball",
    "Book reading ",
    "Dancing, playing, Drawing ",
    "I like to write songs and poems and talking to older experienced people ",
    "Playing football ",
    "Playing flute,guitar, solo travelling",
    "Writing, Listening Music, Cooking ",
    "My hobby is learning new skills,also i love singing.",
    "Poetry, writing, and sketching ",
    "air rifle shooting ",
    "Art,cooking,photography,travelling "
]

# Create the DataFrame
df = pd.DataFrame({"HobbiesAndInterests": hobbies})

# Define broad categories with associated keywords.
# All keywords are in lowercase to ease case-insensitive comparisons.
category_keywords = {
    "Technology and Coding": [
        "coding", "programming", "code", "computing", "cyber security", "tech", "software"
    ],
    "Sports and Fitness": [
        "basketball", "cricket", "football", "badminton", "kabaddi", "gym", "swim",
        "athletics", "karate", "volleyball", "soccer", "outdoor", "sports", "trekking",
        "athlete"
    ],
    "Arts and Crafts": [
        "drawing", "painting", "sketch", "diy", "craft", "calligraphy", "design",
        "mehandi", "rangoli", "illustration"
    ],
    "Music and Dance": [
        "dance", "dancing", "sing", "music", "guitar", "flute", "harmonium", "tabla", "piano", "song"
    ],
    "Reading and Writing": [
        "read", "novel", "book", "poem", "writing", "literature", "story", "novels"
    ],
    "Gaming and Esports": [
        "game", "gaming", "esports", "video game", "pubg", "bgmi"
    ],
    "Travel and Outdoors": [
        "travel", "trek", "trekking", "hiking", "explore", "outing", "adventure", "trip", "vacation", "tour"
    ],
    "Cooking and Food": [
        "cook", "bake", "cuisine", "food", "culinary"
    ],
    "Entertainment and Leisure": [
        "movie", "netflix", "tv", "series", "youtube", "documentary", "film", "webseries"
    ],
    "Social and Personal Development": [
        "organizing", "interaction", "social", "communication", "management", "teamwork",
        "volunteering", "networking"
    ]
}


def map_to_categories(hobby_text):
    """
    Given a hobby string, checks for keywords in each category.
    Returns a comma-separated string of broad categories found.
    If none match, returns 'Other/Miscellaneous'.
    """
    if not isinstance(hobby_text, str) or hobby_text.strip() == "":
        return "Other/Miscellaneous"

    text = hobby_text.lower()
    matched_categories = set()

    for category, keywords in category_keywords.items():
        for keyword in keywords:
            if keyword in text:
                matched_categories.add(category)
                break  # No need to check other keywords in this category

    if matched_categories:
        return ", ".join(sorted(matched_categories))
    else:
        return "Other/Miscellaneous"


